// Model.cs —— 启动面板的数据模型
// 为什么单独一个文件：扫描、图标、配置、UI 四层都要用同一份结构，避免各自造轮子。

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;

namespace BreadLauncher
{
    /// <summary>
    /// 一个可以启动的「应用」。数据来源是 shell:AppsFolder，所以 UWP 和传统 exe 共用同一种模型。
    /// </summary>
    public class AppEntry
    {
        public string Name;
        /// <summary>启动用的路径：传统程序是 exe 全路径；UWP 是 AUMID（如 Microsoft.WindowsCalculator_8wekyb3d8bbwe!App）。</summary>
        public string Path;
        /// <summary>唯一标识（Path 的小写形式），配置里存的就是它。</summary>
        public string Key;
        /// <summary>分组用的首字母：A-Z 或 #（数字、中文、符号）。</summary>
        public string Letter;
        public bool IsPinned;
        /// <summary>最近新出现的应用（第一次见到时记时间，7 天内标记）。</summary>
        public bool IsNew;
        /// <summary>额外图标来源：桌面 .url 里写的 IconFile=，或同名 .lnk 的路径。系统图标取不到时用它兜底。</summary>
        public string IconSource;
        /// <summary>shell 告诉我们的真实目标（只用于 Microsoft.AutoGenerated.* 这类条目），最终没别的图标来源时才用。</summary>
        public string LinkTarget;
        /// <summary>这个条目在桌面上有同名快捷方式（.lnk/.url），或者是直接由桌面快捷方式建出来的。
        /// 用来在选择器里标「桌面」并支持「只看桌面」筛选。</summary>
        public bool OnDesktop;
        /// <summary>来自用户自定义扫描目录（设置里的 ScanDirs；选择器「来源」菜单能按它筛选）。</summary>
        public bool FromCustom;
        /// <summary>用户起的显示名（右键 →「重命名…」，存在 Settings.Renames 里）。空 = 用原名。</summary>
        public string CustomName;
        /// <summary>名字常驻显示（右键 →「名字常驻显示」）：一直画在图标下面，不用悬停。</summary>
        public bool ShowName;

        /// <summary>**界面上该显示的名字**：有自定义名就用它，否则用扫描到的原名。
        /// ★所有要显示名字的地方（列表行、悬停提示、复制名字、自检匹配）都用这个，别直接用 Name。</summary>
        public string DisplayName
        {
            get { return string.IsNullOrEmpty(CustomName) ? Name : CustomName; }
        }

        public AppEntry()
        {
        }

        public AppEntry(string name, string path)
        {
            Name = CleanName(name);
            Path = (path ?? string.Empty).Trim();
            Refresh();
        }

        public void Refresh()
        {
            Key = (Path ?? string.Empty).Trim().ToLowerInvariant();
            Letter = ComputeLetter(Name);
        }

        /// <summary>启动时到底该用哪种方式：文件存在就直接启动，否则当成 shell:AppsFolder 的 AUMID。</summary>
        public bool IsRealFile
        {
            get
            {
                // 这里每次都问文件系统：AppsFolder 里传统程序的 Path 就是 exe 全路径，
                // UWP 的 Path 是 AUMID（不可能存在同名文件），两者靠这个区分最可靠。
                return !string.IsNullOrEmpty(Path) && System.IO.File.Exists(Path);
            }
        }

        /// <summary>去掉开始菜单里常见的后缀噪声，比如「xxx - 快捷方式」。</summary>
        public static string CleanName(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return string.Empty;
            string s = raw.Trim();
            string[] tails = new string[] { " - 快捷方式", " - Shortcut", " 快捷方式" };
            for (int i = 0; i < tails.Length; i++)
            {
                if (s.EndsWith(tails[i], StringComparison.OrdinalIgnoreCase))
                {
                    s = s.Substring(0, s.Length - tails[i].Length).Trim();
                    break;
                }
            }
            return s;
        }

        private static string ComputeLetter(string name)
        {
            if (string.IsNullOrEmpty(name)) return "#";
            // 先去掉开头的空白和引号，避免「“某应用”」被分到 # 里
            string s = name.TrimStart(' ', '"', '\u201c', '\u300c', '\'');
            if (s.Length == 0) return "#";
            return PinyinLetter.Of(s[0]);
        }

        public override string ToString()
        {
            return Name + " <" + Path + ">";
        }
    }

    /// <summary>
    /// 自定义显示名的读写（右键应用 →「重命名…」）。名字按 `AppEntry.Key` 存在 `Settings.Renames` 里 ——
    /// **跨分组、跨重启都生效**（不是存在某个分组上）。
    /// ★注意：改的只是「显示名」，`Name` 保持扫描到的原名不变（去重、扫描、缓存都靠原名/Key，别去改它）。
    /// </summary>
    public static class AppNames
    {
        /// <summary>查这个 Key 的自定义名；没有返回 null。</summary>
        public static string Lookup(Settings s, string key)
        {
            if (s == null || s.Renames == null || string.IsNullOrEmpty(key)) return null;
            string v;
            if (s.Renames.TryGetValue(key, out v) == false) return null;
            return string.IsNullOrEmpty(v) ? null : v;
        }

        /// <summary>这个 Key 是不是「名字常驻显示」。</summary>
        public static bool IsLabeled(Settings s, string key)
        {
            if (s == null || s.NameLabels == null || string.IsNullOrEmpty(key)) return false;
            for (int i = 0; i < s.NameLabels.Count; i++)
                if (string.Equals(s.NameLabels[i], key, StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        /// <summary>开/关「名字常驻显示」（写 Settings.NameLabels + 更新条目上的 ShowName）。</summary>
        public static void SetLabel(Settings s, AppEntry en, bool on)
        {
            if (s == null || en == null || string.IsNullOrEmpty(en.Key)) return;
            if (s.NameLabels == null) s.NameLabels = new List<string>();
            for (int i = s.NameLabels.Count - 1; i >= 0; i--)
                if (string.Equals(s.NameLabels[i], en.Key, StringComparison.OrdinalIgnoreCase)) s.NameLabels.RemoveAt(i);
            if (on) s.NameLabels.Add(en.Key);
            en.ShowName = on;
        }

        /// <summary>设/清自定义名（空字符串 = 恢复原名）。同时把条目上的 CustomName 更新掉。</summary>
        public static void Set(Settings s, AppEntry en, string name)
        {
            if (s == null || en == null || string.IsNullOrEmpty(en.Key)) return;
            if (s.Renames == null) s.Renames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            string v = (name ?? string.Empty).Trim();
            if (v.Length == 0) s.Renames.Remove(en.Key);
            else s.Renames[en.Key] = v;
            en.CustomName = v.Length == 0 ? null : v;
        }

        /// <summary>扫描/读缓存之后，把设置里记着的自定义名刷到所有条目上。</summary>
        public static void ApplyAll(Settings s, List<AppEntry> list)
        {
            if (s == null || list == null) return;
            for (int i = 0; i < list.Count; i++)
            {
                AppEntry en = list[i];
                if (en == null) continue;
                en.CustomName = Lookup(s, en.Key);
                en.ShowName = IsLabeled(s, en.Key);
            }
        }
    }
}